#!/usr/bin/env python3
"""Generates src/TangNanoVocoder/data/default_vocoder_image.h: the FPGA's
program image (vocoder_model --export-hw) as a C array, for the MCU to
upload over the link (VocoderClient::uploadProgram()).

  tools/make_image_header.py [IMAGE.bin]

Without an argument, the image is exported with model/build/vocoder_model
(build it first: cmake -S model -B model/build && cmake --build model/build).
"""
import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "TangNanoVocoder", "data", "default_vocoder_image.h")
MODEL = os.path.join(ROOT, "model", "build", "vocoder_model")


def main():
    if len(sys.argv) > 1:
        data = open(sys.argv[1], "rb").read()
    else:
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "image.bin")
            subprocess.run([MODEL, "--text", "Hello world!", "--export-hw", path], check=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            data = open(path, "rb").read()
    h = struct.unpack("<16I", data[:64])
    if h[0] != 0x48564E54 or h[10] * 4 != len(data):
        sys.exit("not a TNVH image")
    z_scale = struct.unpack("<f", struct.pack("<I", h[11]))[0]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("#pragma once\n")
        f.write("// default_vocoder_image: the Tang Nano 20K vocoder's program image\n")
        f.write("// (model/build/vocoder_model --export-hw; format in docs/gateware.md): the\n")
        f.write(f"// quantized TinyTTS vocoder, {h[2]} ops, sentences up to {h[4]} latent frames,\n")
        f.write(f"// latent scale {z_scale:.9g}. Generated by tools/make_image_header.py - do not edit.\n")
        f.write("// Include it in one translation unit only.\n")
        f.write("#include <stddef.h>\n#include <stdint.h>\n\n")
        f.write("alignas(4) inline const uint8_t default_vocoder_image[] = {\n")
        for i in range(0, len(data), 24):
            f.write("  " + ", ".join("0x%02x" % b for b in data[i:i + 24]) + ",\n")
        f.write("};\n")
        f.write(f"inline const size_t default_vocoder_image_len = {len(data)};\n")
    print(f"wrote {OUT}: {len(data)} bytes")


if __name__ == "__main__":
    main()
