#!/usr/bin/env python3
"""Generates src/TangNanoVocoder/data/default_frontend_weights.h: the part of
TinyTTS's weights the MCU needs when the FPGA runs the flow and the vocoder -
text encoder (enc_p.*), duration predictor (dp.*) and speaker embedding
(emb_g.*) - in TinyTTS's named-tensor format (WeightStore.h), for
tnv::FrontEnd. 0.66MB instead of all 2.07MB.

  tools/make_frontend_weights.py [WEIGHTS.bin]

Default input: research/weights.bin of the TinyTTS checkout next to this
repository.
"""
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "TangNanoVocoder", "data", "default_frontend_weights.h")
DEFAULT_IN = os.path.join(os.path.dirname(ROOT), "TinyTTS", "research", "weights.bin")
KEEP = ("enc_p", "dp", "emb_g")


def frontend_tensors(data):
    """The kept tensors' records, unchanged, and their names."""
    pos, out, names = 0, bytearray(), []
    while pos + 4 <= len(data):
        start = pos
        n = struct.unpack_from("<i", data, pos)[0]
        pos += 4
        if n == 0:
            break
        name = data[pos:pos + n].decode()
        pos += n
        nd = struct.unpack_from("<i", data, pos)[0]
        pos += 4
        shape = struct.unpack_from("<%di" % nd, data, pos)
        pos += 4 * nd
        dtype = struct.unpack_from("<i", data, pos)[0]
        pos += 4
        total = 1
        for d in shape:
            total *= d
        pos += (shape[0] * 4 + total) if dtype == 2 else total * (4 if dtype == 0 else 2)
        if name.split(".")[0] in KEEP:
            out += data[start:pos]
            names.append(name)
    out += struct.pack("<i", 0)  # end marker
    return bytes(out), names


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_IN
    data = open(src, "rb").read()
    out, names = frontend_tensors(data)
    for needed in ("enc_p.proj.weight", "dp.proj.weight", "emb_g.weight"):
        if needed not in names:
            sys.exit(f"{src}: no {needed} - not TinyTTS weights?")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("#pragma once\n")
        f.write("// default_frontend_weights: TinyTTS's text encoder, duration predictor and\n")
        f.write(f"// speaker embedding ({len(names)} tensors of {os.path.basename(src)}), for tnv::FrontEnd -\n")
        f.write("// all the MCU needs when the FPGA runs the flow and the vocoder.\n")
        f.write("// Generated by tools/make_frontend_weights.py - do not edit.\n")
        f.write("// Include it in one translation unit only.\n")
        f.write("#include <stddef.h>\n#include <stdint.h>\n\n")
        f.write("alignas(4) inline const uint8_t default_frontend_weights[] = {\n")
        for i in range(0, len(out), 24):
            f.write("  " + ", ".join("0x%02x" % b for b in out[i:i + 24]) + ",\n")
        f.write("};\n")
        f.write(f"inline const size_t default_frontend_weights_len = {len(out)};\n")
    print(f"wrote {OUT}: {len(out)} bytes ({len(names)} tensors, of {len(data)} bytes)")


if __name__ == "__main__":
    main()
